In [4]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.feature_selection import f_classif
import plotly.io as pio
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import umap.umap_ as umap

In [5]:
# Load the dataset
df = pd.read_csv("../data/features_audio_subset_new.csv")

# Extract country and style from the filename (assuming a specific pattern)
df["country"] = df["filename"].apply(lambda x: x.split("_")[0])
df["style"] = df["filename"].apply(lambda x: x.split("_")[1])
df["track_id"] = df["filename"].apply(lambda x: x.replace(".wav", ""))

In [7]:
# Select relevant features for dimensionality reduction
feature_cols = [col for col in df.columns if col.startswith(("mfcc", "centroid", "rolloff", "bandwidth", "zcr", "flatness", "harmonic_", "percussive_"))]
X = df[feature_cols].copy()

# Normalize the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
y = df["style"]

In [16]:
f_scores, p_values = f_classif(X_scaled, df["style"])
anova_df = pd.DataFrame({
    "feature": feature_cols,
    "f_score": f_scores,
    "p_value": p_values
}).sort_values(by="f_score", ascending=False)

top_features = anova_df.head(10)

fig = go.Figure(
    go.Bar(
        x=top_features["feature"][::-1],
        y=top_features["f_score"][::-1],
        orientation='h',
        marker=dict(color=top_features["f_score"][::-1], colorscale="YlGnBu"),
    )
)

fig.update_layout(
    title="Top 10 Features by ANOVA F-Score",
    xaxis_title="F-score",
    yaxis_title="Feature",
    height=800,
    margin=dict(l=150, r=50, t=50, b=50),
)
fig.show()

In [4]:
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

df["pca_1"] = X_pca[:, 0]
df["pca_2"] = X_pca[:, 1]

In [5]:
tsne = TSNE(n_components=2, perplexity=5, random_state=42) # perplexity 5 is good for small datasets
X_tsne = tsne.fit_transform(X_scaled)

df["tsne_1"] = X_tsne[:, 0]
df["tsne_2"] = X_tsne[:, 1]

In [6]:
reducer = umap.UMAP(n_components=2, random_state=42)
X_umap = reducer.fit_transform(X_scaled)

df["umap_1"] = X_umap[:, 0]
df["umap_2"] = X_umap[:, 1]

/home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

In [ ]:
# !pip install -U kaleido

Requirement already satisfied: kaleido in /home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages (1.0.0)
Requirement already satisfied: choreographer>=1.0.5 in /home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages (from kaleido) (1.0.9)
Requirement already satisfied: logistro>=1.0.8 in /home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages (from kaleido) (1.1.0)
Requirement already satisfied: orjson>=3.10.15 in /home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages (from kaleido) (3.10.18)
Requirement already satisfied: packaging in /home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages (from kaleido) (25.0)
Requirement already satisfied: simplejson>=3.19.3 in /home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages (from choreographer>=1.0.5->kaleido) (3.20.1)

In [12]:
fig = px.scatter(df, x="pca_1", y="pca_2",
                 color="country", symbol="style",
                 hover_name="track_id",
                 title="Timbre Space - PCA Projection")

fig.update_layout(
    title="Timbre Space - PCA Projection",
    width=600,
    height=400,
    font=dict(size=16),
    margin=dict(l=10, r=10, t=50, b=50),  # margem superior e inferior maiores
    legend=dict(
        title="", 
        orientation="h", 
        yanchor="top",
        y=-0.2,  # legenda abaixo do gráfico
        xanchor="center",
        x=0.5,
        font=dict(size=16)
    ),
    title_x=0.5
)
pio.write_image(fig, "../images/timbre_space_pca.png", format="png", scale=3)


fig.show()

In [ ]:
fig = px.scatter(df, x="tsne_1", y="tsne_2",
                 color="country", symbol="style",
                 hover_name="track_id",
                 title="Timbre Space - t-SNE Projection")
fig.update_layout(
    title="Timbre Space - t-SNE Projection",
    width=600,
    height=400,
    font=dict(size=16),
    margin=dict(l=10, r=10, t=50, b=50),
    legend=dict(
        title="", 
        orientation="h", 
        yanchor="top",
        y=-0.2,  # legend below the graph
        xanchor="center",
        x=0.5,
        font=dict(size=16)
    ),
    title_x=0.5
)
pio.write_image(fig, "../images/timbre_space_tsne.png", format="png", scale=3)

fig.show()

In [ ]:
fig = px.scatter(df, x="umap_1", y="umap_2",
                 color="country", symbol="style",
                 hover_name="track_id",
                 title="Timbre Space - UMAP Projection")
fig.update_layout(
    title="Timbre Space - UMAP Projection",
    width=600,
    height=400,
    font=dict(size=16),
    margin=dict(l=10, r=10, t=50, b=50),  
    legend=dict(
        title="", 
        orientation="h", 
        yanchor="top",
        y=-0.2,  # legend below the graph
        xanchor="center",
        x=0.5,
        font=dict(size=16)
    ),
    title_x=0.5
)
pio.write_image(fig, "../images/timbre_space_umap.png", format="png", scale=3)
fig.show()

In [24]:
from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score

def evaluate_embedding(X, labels):
    sil = silhouette_score(X, labels)
    cal = calinski_harabasz_score(X, labels)
    dbi = davies_bouldin_score(X, labels)
    return sil, cal, dbi

results = {}

# PCA
results["PCA"] = evaluate_embedding(df[["pca_1", "pca_2"]], df["country"])
# results["PCA_style"] = evaluate_embedding(df[["pca_1", "pca_2"]], df["style"])

# t-SNE
results["tSNE"] = evaluate_embedding(df[["tsne_1", "tsne_2"]], df["country"])
# results["tSNE_style"] = evaluate_embedding(df[["tsne_1", "tsne_2"]], df["style"])

# UMAP
results["UMAP"] = evaluate_embedding(df[["umap_1", "umap_2"]], df["country"])
# results["UMAP_style"] = evaluate_embedding(df[["umap_1", "umap_2"]], df["style"])

In [25]:
summary = pd.DataFrame(results, index=["Silhouette", "Calinski-Harabasz", "Davies-Bouldin"]).T
summary = summary.round(3)
summary

      Silhouette  Calinski-Harabasz  Davies-Bouldin
PCA        0.050             16.537           3.429
tSNE       0.064              9.440           2.715
UMAP       0.138             22.736           2.085

In [26]:
from sklearn.cluster import KMeans

# Aplica KMeans com 6 clusters
kmeans = KMeans(n_clusters=3, random_state=42)
df["cluster_kmeans"] = kmeans.fit_predict(X_scaled)

In [27]:
# Avaliação dos clusters em cada espaço projetado
results["PCA_kmeans"] = evaluate_embedding(df[["pca_1", "pca_2"]], df["cluster_kmeans"])
results["tSNE_kmeans"] = evaluate_embedding(df[["tsne_1", "tsne_2"]], df["cluster_kmeans"])
results["UMAP_kmeans"] = evaluate_embedding(df[["umap_1", "umap_2"]], df["cluster_kmeans"])

In [ ]:
# Visualização dos clusters - PCA
fig = px.scatter(df, x="pca_1", y="pca_2",
                 color=df["cluster_kmeans"].astype(str),
                 hover_name="track_id",
                 title="KMeans Clusters - PCA Projection")
fig.update_layout(
    width=600,
    height=400,
    font=dict(size=16),
    margin=dict(l=10, r=10, t=50, b=50),  
    legend=dict(
        title="", 
        orientation="h", 
        yanchor="top",
        y=-0.2,  # legend below the graph
        xanchor="center",
        x=0.5,
        font=dict(size=16)
    ),
    title_x=0.5
)
pio.write_image(fig, "../images/kmeans_clusters_pca.png", format="png", scale=3)
fig.show()

In [ ]:
# Visualização dos clusters - t-SNE
fig = px.scatter(df, x="tsne_1", y="tsne_2",
                 color=df["cluster_kmeans"].astype(str),
                 hover_name="track_id",
                 title="KMeans Clusters - t-SNE Projection")
fig.update_layout(
    width=600,
    height=400,
    font=dict(size=16),
    margin=dict(l=10, r=10, t=50, b=50),  
    legend=dict(
        title="", 
        orientation="h", 
        yanchor="top",
        y=-0.2,  # legend below the graph
        xanchor="center",
        x=0.5,
        font=dict(size=16)
    ),
    title_x=0.5
)
pio.write_image(fig, "../images/kmeans_clusters_tsne.png", format="png", scale=3)
fig.show()

In [ ]:
# Visualização dos clusters - UMAP
fig = px.scatter(df, x="umap_1", y="umap_2",
                 color=df["cluster_kmeans"].astype(str),
                 hover_name="track_id",
                 title="KMeans Clusters - UMAP Projection")
fig.update_layout(
    width=600,
    height=400,
    font=dict(size=16),
    margin=dict(l=10, r=10, t=50, b=50),
    legend=dict(
        title="", 
        orientation="h", 
        yanchor="top",
        y=-0.2,  # legend below the graph
        xanchor="center",
        x=0.5,
        font=dict(size=16)
    ),
    title_x=0.5
)
pio.write_image(fig, "../images/kmeans_clusters_umap.png", format="png", scale=3)
fig.show()

In [31]:
# Atualiza sumário com os resultados dos clusters
summary = pd.DataFrame(results, index=["Silhouette", "Calinski-Harabasz", "Davies-Bouldin"]).T
summary = summary.round(3)
summary

             Silhouette  Calinski-Harabasz  Davies-Bouldin
PCA               0.050             16.537           3.429
tSNE              0.064              9.440           2.715
UMAP              0.138             22.736           2.085
PCA_kmeans        0.095             31.722          29.412
tSNE_kmeans       0.195             33.381           1.393
UMAP_kmeans       0.260             46.761           1.195

In [32]:
import hdbscan

In [33]:
# Aplica HDBSCAN no espaço UMAP (mais promissor até agora)
clusterer = hdbscan.HDBSCAN(min_cluster_size=8)
df["cluster_hdbscan"] = clusterer.fit_predict(df[["umap_1", "umap_2"]])

df["cluster_hdbscan_Tsnee"] = clusterer.fit_predict(df[["tsne_1", "tsne_2"]])

df["cluster_hdbscan_PCA"] = clusterer.fit_predict(df[["pca_1", "pca_2"]])

/home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

/home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

/home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

/home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

/home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

/home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

In [ ]:
# Visualiza clusters HDBSCAN - TSNE
fig = px.scatter(df, x="tsne_1", y="tsne_2",
                    color=df["cluster_hdbscan"].astype(str),
                    hover_name="track_id",
                    title="HDBSCAN Clusters - t-SNE Projection")
fig.update_layout(
    width=600,
    height=400,
    font=dict(size=16),
    margin=dict(l=10, r=10, t=50, b=50),
    legend=dict(
        title="", 
        orientation="h", 
        yanchor="top",
        y=-0.2,  # legend below the graph
        xanchor="center",
        x=0.5,
        font=dict(size=16)
    ),
    title_x=0.5
)
pio.write_image(fig, "../images/hdbscan_tsne.png", format="png", scale=3)
fig.show()

In [ ]:
# Visualização dos clusters HDBSCAN - PCA
fig = px.scatter(df, x="pca_1", y="pca_2",
                 color=df["cluster_hdbscan"].astype(str),
                 hover_name="track_id",
                 title="HDBSCAN Clusters - PCA Projection")
fig.update_layout(
    width=600,
    height=400,
    font=dict(size=16),
    margin=dict(l=10, r=10, t=50, b=50), 
    legend=dict(
        title="", 
        orientation="h", 
        yanchor="top",
        y=-0.2,  # legend below the graph
        xanchor="center",
        x=0.5,
        font=dict(size=16)
    ),
    title_x=0.5
)
pio.write_image(fig, "../images/hdbscan_pca.png", format="png", scale=3)
fig.show()

In [ ]:
# Visualiza clusters encontrados
fig = px.scatter(df, x="umap_1", y="umap_2",
                 color=df["cluster_hdbscan"].astype(str),
                 hover_name="track_id",
                 title="HDBSCAN Clusters - UMAP Projection")
fig.update_layout(
    width=600,
    height=400,
    font=dict(size=16),
    margin=dict(l=10, r=10, t=50, b=50), 
    legend=dict(
        title="", 
        orientation="h", 
        yanchor="top",
        y=-0.2,  # legend below the graph
        xanchor="center",
        x=0.5,
        font=dict(size=16)
    ),
    title_x=0.5
)
pio.write_image(fig, "../images/hdbscan_umap.png", format="png", scale=3)
fig.show()

In [ ]:
# Define a mask to filter out outliers and evaluate the embeddings
mask_UMAP = df["cluster_hdbscan"] != -1
mask_Tsne = df["cluster_hdbscan_Tsnee"] != -1
mask_PCA = df["cluster_hdbscan_PCA"] != -1

# results["tSNE_hdbscan"] = evaluate_embedding(df[["tsne_1", "tsne_2"]][mask_Tsne], df["cluster_hdbscan_Tsnee"][mask_Tsne])
# results["PCA_hdbscan"] = evaluate_embedding(df[["pca_1", "pca_2"]][mask_PCA], df["cluster_hdbscan_PCA"][mask_PCA])
results["UMAP_hdbscan"] = evaluate_embedding(df[["umap_1", "umap_2"]][mask_UMAP], df["cluster_hdbscan"][mask_UMAP])

In [ ]:
# Update summary with HDBSCAN results
summary = pd.DataFrame(results, index=["Silhouette", "Calinski-Harabasz", "Davies-Bouldin"]).T
summary = summary.round(3)
summary

              Silhouette  Calinski-Harabasz  Davies-Bouldin
PCA                0.050             16.537           3.429
tSNE               0.064              9.440           2.715
UMAP               0.138             22.736           2.085
PCA_kmeans         0.095             31.722          29.412
tSNE_kmeans        0.195             33.381           1.393
UMAP_kmeans        0.260             46.761           1.195
UMAP_hdbscan       0.535             55.737           0.529

In [ ]:
print("Found clusters:")
print(df["cluster_hdbscan"].value_counts())

Clusters encontrados pelo HDBSCAN com umap:
cluster_hdbscan
-1    42
 1    39
 0    10
Name: count, dtype: int64