In [36]:
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import umap.umap_ as umap

In [37]:
# Carrega os dados extraídos do áudio
df = pd.read_csv("../data/features_audio_subset_new.csv")

# Extrai país e estilo a partir do nome do arquivo (assumindo padrão no nome)
df["country"] = df["filename"].apply(lambda x: x.split("_")[0])
df["style"] = df["filename"].apply(lambda x: x.split("_")[1])
df["track_id"] = df["filename"].apply(lambda x: x.replace(".wav", ""))

In [ ]:
# Seleciona apenas colunas numéricas
feature_cols = [col for col in df.columns if col.startswith(("mfcc", "centroid", "rolloff", "zcr", "flatness", "harmonic_", "percussive_"))]
X = df[feature_cols].copy()

# Normaliza os dados
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

['mfcc1_mean',
 'mfcc2_mean',
 'mfcc3_mean',
 'mfcc4_mean',
 'mfcc5_mean',
 'mfcc6_mean',
 'mfcc7_mean',
 'mfcc8_mean',
 'mfcc9_mean',
 'mfcc10_mean',
 'mfcc11_mean',
 'mfcc12_mean',
 'mfcc13_mean',
 'mfcc1_std',
 'mfcc2_std',
 'mfcc3_std',
 'mfcc4_std',
 'mfcc5_std',
 'mfcc6_std',
 'mfcc7_std',
 'mfcc8_std',
 'mfcc9_std',
 'mfcc10_std',
 'mfcc11_std',
 'mfcc12_std',
 'mfcc13_std',
 'centroid_mean',
 'centroid_std',
 'rolloff_mean',
 'rolloff_std',
 'harmonic_chroma1_mean',
 'harmonic_chroma2_mean',
 'harmonic_chroma3_mean',
 'harmonic_chroma4_mean',
 'harmonic_chroma5_mean',
 'harmonic_chroma6_mean',
 'harmonic_chroma7_mean',
 'harmonic_chroma8_mean',
 'harmonic_chroma9_mean',
 'harmonic_chroma10_mean',
 'harmonic_chroma11_mean',
 'harmonic_chroma12_mean',
 'harmonic_chroma1_std',
 'harmonic_chroma2_std',
 'harmonic_chroma3_std',
 'harmonic_chroma4_std',
 'harmonic_chroma5_std',
 'harmonic_chroma6_std',
 'harmonic_chroma7_std',
 'harmonic_chroma8_std',
 'harmonic_chroma9_std',
 'harmonic_chroma10_std',
 'harmonic_chroma11_std',
 'harmonic_chroma12_std',
 'harmonic_tonnetz1_mean',
 'harmonic_tonnetz2_mean',
 'harmonic_tonnetz3_mean',
 'harmonic_tonnetz4_mean',
 'harmonic_tonnetz5_mean',
 'harmonic_tonnetz6_mean',
 'harmonic_tonnetz1_std',
 'harmonic_tonnetz2_std',
 'harmonic_tonnetz3_std',
 'harmonic_tonnetz4_std',
 'harmonic_tonnetz5_std',
 'harmonic_tonnetz6_std',
 'percussive_zcr_mean',
 'percussive_zcr_std',
 'percussive_flatness_mean',
 'percussive_flatness_std',
 'percussive_rms_mean',
 'percussive_rms_std']

In [40]:
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

df["pca_1"] = X_pca[:, 0]
df["pca_2"] = X_pca[:, 1]

In [ ]:
tsne = TSNE(n_components=2, perplexity=5, random_state=42) # perplexity 5 is good for small datasets
X_tsne = tsne.fit_transform(X_scaled)

df["tsne_1"] = X_tsne[:, 0]
df["tsne_2"] = X_tsne[:, 1]

In [42]:
reducer = umap.UMAP(n_components=2, random_state=42)
X_umap = reducer.fit_transform(X_scaled)

df["umap_1"] = X_umap[:, 0]
df["umap_2"] = X_umap[:, 1]

/home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

/home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages/umap/umap_.py:1952: UserWarning:

n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.

In [43]:
fig = px.scatter(df, x="pca_1", y="pca_2",
                 color="country", symbol="style",
                 hover_name="track_id",
                 title="Timbre Space - PCA Projection")
fig.show()

In [44]:
fig = px.scatter(df, x="tsne_1", y="tsne_2",
                 color="country", symbol="style",
                 hover_name="track_id",
                 title="Timbre Space - t-SNE Projection")
fig.show()

In [45]:
fig = px.scatter(df, x="umap_1", y="umap_2",
                 color="country", symbol="style",
                 hover_name="track_id",
                 title="Timbre Space - UMAP Projection")
fig.show()

In [50]:
from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score

def evaluate_embedding(X, labels):
    sil = silhouette_score(X, labels)
    cal = calinski_harabasz_score(X, labels)
    dbi = davies_bouldin_score(X, labels)
    return sil, cal, dbi

results = {}

# PCA
results["PCA"] = evaluate_embedding(df[["pca_1", "pca_2"]], df["country"])
# results["PCA_style"] = evaluate_embedding(df[["pca_1", "pca_2"]], df["style"])

# t-SNE
results["tSNE"] = evaluate_embedding(df[["tsne_1", "tsne_2"]], df["country"])
# results["tSNE_style"] = evaluate_embedding(df[["tsne_1", "tsne_2"]], df["style"])

# UMAP
results["UMAP"] = evaluate_embedding(df[["umap_1", "umap_2"]], df["country"])
# results["UMAP_style"] = evaluate_embedding(df[["umap_1", "umap_2"]], df["style"])

In [51]:
summary = pd.DataFrame(results, index=["Silhouette", "Calinski-Harabasz", "Davies-Bouldin"]).T
summary = summary.round(3)
summary

      Silhouette  Calinski-Harabasz  Davies-Bouldin
PCA        0.052             16.780           3.332
tSNE       0.109             14.420           2.182
UMAP       0.085             14.568           2.266

In [52]:
from sklearn.cluster import KMeans

# Aplica KMeans com 6 clusters
kmeans = KMeans(n_clusters=3, random_state=42)
df["cluster_kmeans"] = kmeans.fit_predict(X_scaled)

In [53]:
# Avaliação dos clusters em cada espaço projetado
results["PCA_kmeans"] = evaluate_embedding(df[["pca_1", "pca_2"]], df["cluster_kmeans"])
results["tSNE_kmeans"] = evaluate_embedding(df[["tsne_1", "tsne_2"]], df["cluster_kmeans"])
results["UMAP_kmeans"] = evaluate_embedding(df[["umap_1", "umap_2"]], df["cluster_kmeans"])

In [54]:
# Visualização dos clusters - PCA
fig = px.scatter(df, x="pca_1", y="pca_2",
                 color=df["cluster_kmeans"].astype(str),
                 hover_name="track_id",
                 title="KMeans Clusters - PCA Projection")
fig.show()

In [55]:
# Visualização dos clusters - t-SNE
fig = px.scatter(df, x="tsne_1", y="tsne_2",
                 color=df["cluster_kmeans"].astype(str),
                 hover_name="track_id",
                 title="KMeans Clusters - t-SNE Projection")
fig.show()

In [56]:
# Visualização dos clusters - UMAP
fig = px.scatter(df, x="umap_1", y="umap_2",
                 color=df["cluster_kmeans"].astype(str),
                 hover_name="track_id",
                 title="KMeans Clusters - UMAP Projection")
fig.show()

In [57]:
# Atualiza sumário com os resultados dos clusters
summary = pd.DataFrame(results, index=["Silhouette", "Calinski-Harabasz", "Davies-Bouldin"]).T
summary = summary.round(3)
summary

             Silhouette  Calinski-Harabasz  Davies-Bouldin
PCA               0.052             16.780           3.332
tSNE              0.109             14.420           2.182
UMAP              0.085             14.568           2.266
PCA_kmeans        0.112             32.114           4.567
tSNE_kmeans       0.276             47.186           1.175
UMAP_kmeans       0.252             28.077           1.440

In [58]:
import hdbscan

In [59]:
# Aplica HDBSCAN no espaço UMAP (mais promissor até agora)
clusterer = hdbscan.HDBSCAN(min_cluster_size=8)
df["cluster_hdbscan"] = clusterer.fit_predict(df[["umap_1", "umap_2"]])

df["cluster_hdbscan_Tsnee"] = clusterer.fit_predict(df[["tsne_1", "tsne_2"]])

df["cluster_hdbscan_PCA"] = clusterer.fit_predict(df[["pca_1", "pca_2"]])

/home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

/home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

/home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

/home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

/home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

/home/satan/miniconda3/envs/timbre_env/lib/python3.10/site-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

In [60]:
# Visualiza clusters HDBSCAN - TSNE
fig = px.scatter(df, x="tsne_1", y="tsne_2",
                    color=df["cluster_hdbscan"].astype(str),
                    hover_name="track_id",
                    title="HDBSCAN Clusters - t-SNE Projection")
fig.show()

In [61]:
# Visualização dos clusters HDBSCAN - PCA
fig = px.scatter(df, x="pca_1", y="pca_2",
                 color=df["cluster_hdbscan"].astype(str),
                 hover_name="track_id",
                 title="HDBSCAN Clusters - PCA Projection")
fig.show()

In [62]:
# Visualiza clusters encontrados
fig = px.scatter(df, x="umap_1", y="umap_2",
                 color=df["cluster_hdbscan"].astype(str),
                 hover_name="track_id",
                 title="HDBSCAN Clusters - UMAP Projection")
fig.show()

In [63]:
# Avalia os agrupamentos (ignorando outliers rotulados como -1)
mask_UMAP = df["cluster_hdbscan"] != -1
mask_Tsne = df["cluster_hdbscan_Tsnee"] != -1
mask_PCA = df["cluster_hdbscan_PCA"] != -1

results["tSNE_hdbscan"] = evaluate_embedding(df[["tsne_1", "tsne_2"]][mask_Tsne], df["cluster_hdbscan_Tsnee"][mask_Tsne])
# results["PCA_hdbscan"] = evaluate_embedding(df[["pca_1", "pca_2"]][mask_PCA], df["cluster_hdbscan_PCA"][mask_PCA])
results["UMAP_hdbscan"] = evaluate_embedding(df[["umap_1", "umap_2"]][mask_UMAP], df["cluster_hdbscan"][mask_UMAP])

In [64]:
# Atualiza o sumário
summary = pd.DataFrame(results, index=["Silhouette", "Calinski-Harabasz", "Davies-Bouldin"]).T
summary = summary.round(3)
summary

              Silhouette  Calinski-Harabasz  Davies-Bouldin
PCA                0.052             16.780           3.332
tSNE               0.109             14.420           2.182
UMAP               0.085             14.568           2.266
PCA_kmeans         0.112             32.114           4.567
tSNE_kmeans        0.276             47.186           1.175
UMAP_kmeans        0.252             28.077           1.440
tSNE_hdbscan       0.387             29.999           0.670
UMAP_hdbscan       0.500             48.843           0.544

In [65]:
print("Clusters encontrados pelo HDBSCAN com umap:")
print(df["cluster_hdbscan"].value_counts())

Clusters encontrados pelo HDBSCAN com umap:
cluster_hdbscan
-1    41
 1    40
 0    10
Name: count, dtype: int64